### ISSUE TITLE
true cannot be overridden with false

### ISSUE THREAD

**Issue by dvrensk** [elabs/econfig#12]
This is vaguely related to #9 (which probably should be closed since it seems to be implemented).  I'm all for not supporting booleans but now that the cat is out of the bag, this could be a fun case to look at.  Values in `secrets.yml` usually override those in `app.yml`, but not here:

```yaml
# in app.yml
development:
  foo: true
  bar: false
```
```yaml
# in secrets.yml
development:
  foo: false
  bar: true
```

```
pry(main)> MyApp.config.foo
=> true
pry(main)> MyApp.config.bar
=> true
```
